/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROYECTO2;

import java.util.Calendar;
import eventos.editarmusica;
import eventos.religiososedito;
import eventos.Editardeportec;
import eventos.cancelarmusica;
import java.util.Date;
import javax.swing.JOptionPane;
import porsiacaso.primerusuario;

/**
 *
 * @author 50496
 */
public class CANCELARMUSICA extends javax.swing.JFrame {
    
    BUSCARCODIGO3 op = new BUSCARCODIGO3();

    /**
     * Creates new form CANCELARMUSICA
     */
    public CANCELARMUSICA() {
        initComponents();
        llenado();
        llenar();
        codigo1.setEditable(false);
        titulo.setEditable(false);
        descrip.setEditable(false);
        fecha1.setEnabled(false);
        
        tipos.setEditable(false);
        cantidad.setEditable(false);
        orquesta.setEditable(false);
        MONTO.setEditable(false);
        total.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrip = new javax.swing.JTextArea();
        titulo = new javax.swing.JTextField();
        codigo1 = new javax.swing.JTextField();
        tipos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cambio = new javax.swing.JButton();
        regreso1 = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orquesta = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        MONTO = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CODIGO:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(59, 110, 76, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TITULO:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(66, 167, 69, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DESCRIPCION:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 231, 123, 25);
        jPanel1.add(fecha1);
        fecha1.setBounds(141, 324, 160, 29);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("FECHA:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(77, 324, 62, 25);

        descrip.setColumns(20);
        descrip.setRows(5);
        jScrollPane1.setViewportView(descrip);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(141, 231, 286, 83);
        jPanel1.add(titulo);
        titulo.setBounds(141, 170, 286, 24);
        jPanel1.add(codigo1);
        codigo1.setBounds(141, 109, 286, 24);

        jPanel1.add(tipos);
        tipos.setBounds(145, 378, 173, 26);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Genero:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(72, 376, 67, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CANCELAR EVENTO MUSICAL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 10, 400, 32);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad de personas:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(439, 100, 254, 32);

        cambio.setBackground(new java.awt.Color(0, 204, 255));
        cambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/floppy.png"))); // NOI18N
        cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioActionPerformed(evt);
            }
        });
        jPanel1.add(cambio);
        cambio.setBounds(800, 550, 112, 116);

        regreso1.setBackground(new java.awt.Color(0, 204, 255));
        regreso1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regreso1.setForeground(new java.awt.Color(0, 0, 0));
        regreso1.setText("Atras");
        regreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regreso1ActionPerformed(evt);
            }
        });
        jPanel1.add(regreso1);
        regreso1.setBounds(80, 580, 96, 59);

        cantidad.setForeground(new java.awt.Color(0, 0, 0));
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        jPanel1.add(cantidad);
        cantidad.setBounds(699, 105, 139, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("EQUIPO:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 170, 73, 25);

        orquesta.setColumns(20);
        orquesta.setRows(5);
        jScrollPane2.setViewportView(orquesta);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(600, 170, 230, 210);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MONTO:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(510, 430, 75, 25);

        MONTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MONTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MONTOKeyTyped(evt);
            }
        });
        jPanel1.add(MONTO);
        MONTO.setBounds(600, 424, 180, 30);

        total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });
        jPanel1.add(total);
        total.setBounds(600, 470, 180, 33);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Total Lps:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(500, 480, 82, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioActionPerformed
        // TODO add your handling code here:
        String codigo = op.codigo;
        String user = "";
        String code = codigo1.getText();
        String titulos = titulo.getText();
        String descripcion = descrip.getText();
        Calendar fecha = fecha1.getCalendar();
        String tipo = (String) tipos.getSelectedItem();
        String orq = orquesta.getText();
        
        int personas = Integer.parseInt(cantidad.getText());
        double monto = Double.parseDouble(MONTO.getText());
        double totalid = Double.parseDouble(total.getText());
        
        cancelarmusica musa = new cancelarmusica("s", user, code, titulos, descripcion, fecha, personas, monto, totalid, "s", tipo, orq);
        
        musa.cancelar(codigo);
        new menuevento().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_cambioActionPerformed

    private void regreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regreso1ActionPerformed
        // TODO add your handling code here:
        new BUSCARCODIGO3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regreso1ActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed
    public void llenado() {
        for (Musical.Tipom object : Musical.Tipom.values()) {
            tipos.addItem(object.getGeneros());
        }
        
    }

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_cantidadKeyTyped

    private void MONTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MONTOKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            
        }
        
        String montotext = MONTO.getText();
        if (montotext.equals("") == false) {
            double montos = Double.parseDouble(montotext);
            double porcentaje = montos * 0.3;
            
            double totale = montos + porcentaje;
            String totalid = Double.toString(totale);
            total.setText(totalid);
        } else {
            total.setText("0");
        }
    }//GEN-LAST:event_MONTOKeyReleased

    private void MONTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MONTOKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_MONTOKeyTyped

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyTyped
    public void llenar() {
        Calendar fecha = fecha1.getCalendar();
        primerusuario p = new primerusuario("s", "s", "s", "s", 1);
        
        String code = op.codigo;
        String user = p.userin.get(0).getUser();
        
        editarmusica ob = new editarmusica("s", user, code, "s", "s", fecha, 1, 1, 1, "s", "s", "s");
        
        if (ob.mostrar(code, user) == true) {
            String monto = Double.toString(ob.montoM);
            String totalid = Double.toString(ob.totalidM);
            codigo1.setText(ob.codigoM);
            titulo.setText(ob.tituloM);
            descrip.setText(ob.descripcionM);
            fecha1.setCalendar(ob.fechaM);
            String personas = Integer.toString(ob.personasM);
            tipos.setSelectedItem(ob.tipoM);
            cantidad.setText(personas);
            orquesta.setText(ob.nombresorqM);
            MONTO.setText(monto);
            total.setText(totalid);
            
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CANCELARMUSICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CANCELARMUSICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CANCELARMUSICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CANCELARMUSICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CANCELARMUSICA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MONTO;
    private javax.swing.JButton cambio;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField codigo1;
    private javax.swing.JTextArea descrip;
    private com.toedter.calendar.JDateChooser fecha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea orquesta;
    private javax.swing.JButton regreso1;
    private javax.swing.JComboBox<String> tipos;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
