/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROYECTO2;

import porsiacaso.limitado;
import porsiacaso.primerusuario;
import porsiacaso.contenido;
import porsiacaso.USUARIOS;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 50496
 */
public class LOGIN extends javax.swing.JFrame {

    String tipo = "ADMINISTRADOR";
    String user = "admin";
    String password = "supersecreto";
    String nombre = "";
    int edad = 0;
    static int intentos = 0;
    USUARIOS op = new primerusuario(tipo, user, password, nombre, edad);
    primerusuario prod = (primerusuario) op;

    contenido con = new contenido("CONTENIDO", "ELKYN", "elkyn", "santos", 21);
    limitado lim = new limitado("ILIMITADO", "ELKYN", "elkyn", "santos", 21);

    public LOGIN() {
        if (intentos < 1) {
            prod.agregar(tipo, nombre, user, password, edad);

            intentos++;
        }
        initComponents();
        validacion2.setVisible(false);
        validacion3.setVisible(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        validacion3 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        entrar = new javax.swing.JButton();
        validacion2 = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("JAVA TICKETS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 230, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USUARIO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 40));

        validacion3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        validacion3.setForeground(new java.awt.Color(0, 0, 0));
        validacion3.setText("*CAMPO REQUERIDO");
        jPanel1.add(validacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 140, 30));

        usuario1.setForeground(new java.awt.Color(51, 0, 51));
        usuario1.setToolTipText("");
        jPanel1.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 240, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("CONTRASENA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 282, 240, 30));

        entrar.setBackground(new java.awt.Color(51, 204, 255));
        entrar.setForeground(new java.awt.Color(0, 0, 51));
        entrar.setText("INGRESAR");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        jPanel1.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 160, 50));

        validacion2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        validacion2.setForeground(new java.awt.Color(0, 0, 0));
        validacion2.setText("*CAMPO REQUERIDO");
        jPanel1.add(validacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 140, 30));

        SALIR.setBackground(new java.awt.Color(51, 204, 255));
        SALIR.setForeground(new java.awt.Color(0, 0, 51));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        jPanel1.add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-blue-background-free-download-png-and-psd-files-image_124067.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:

        String users = usuario1.getText();
        String passwords = contra.getText();
        if (validar() == false) {
            if (prod.buscar(users, passwords) == true) {

                new MENUPRINCIPAL().setVisible(true);
                this.dispose();

            } else if (con.buscar(users, passwords) == true) {
                new MENUPRINCIPAL().setVisible(true);
                this.dispose();
            } else if (lim.buscar(users, passwords) == true) {
                new MENUPRINCIPAL().setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "USUARIO NO ENCONTRADO");
            }
        }
    }//GEN-LAST:event_entrarActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    public boolean validar() {
        if (usuario1.getText().equals("") || contra.getText().equals("")) {
            validacion2.setVisible(true);
            validacion3.setVisible(true);
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new LOGIN().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SALIR;
    private javax.swing.JPasswordField contra;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usuario1;
    private javax.swing.JLabel validacion2;
    private javax.swing.JLabel validacion3;
    // End of variables declaration//GEN-END:variables
}
